services:
  dominus-admin:
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/dominus-admin
    ports:
      - "9001:9000"
    user: "www-data"
    environment:
      SYMFONY_ENV: dev
      APP_ENV: dev
      INIT_XDEBUG_ACTIVATED: 1
      DOMINUS_API_ENDPOINT: http://dominus-api-api-nginx-1
    networks:
      - dominus-network

  da-node:
    image: "node:20"
    working_dir: "/home/node/app"
    environment:
      - NODE_ENV=dev
    tty: true
    stdin_open: true
    volumes:
      - ./:/home/node/app
    networks:
      - dominus-network

  da-nginx:
    image: nginx:stable-alpine
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dominus-admin.rule=Host(`dominus-admin.localhost`)"
      - "traefik.http.routers.dominus-admin.entrypoints=websecure"
      - "traefik.http.routers.dominus-admin.tls.certresolver=le"
    volumes:
      - ./:/var/www/dominus-admin
      - ./docker/nginx/dominus-admin.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/certificates:/etc/nginx/certificates
    depends_on:
      - dominus-admin
    networks:
      - dominus-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  dominus-network:
    external: true
