services:
  dominus-admin:
    build:
      context: docker/frankenphp
    restart: unless-stopped
    environment:
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      # Run "composer require symfony/mercure-bundle" to install and configure the Mercure integration
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://php/.well-known/mercure}
      MERCURE_PUBLIC_URL: ${CADDY_MERCURE_PUBLIC_URL:-https://${SERVER_NAME:-localhost}:${HTTPS_PORT:-443}/.well-known/mercure}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      DOMINUS_API_ENDPOINT: http://dominus-api-dominus-api-1
    volumes:
      - ./:/app
      - caddy_data:/data
      - caddy_config:/config
      - ./docker/frankenphp/Caddyfile:/etc/frankenphp/Caddyfile
      - ./docker/frankenphp/conf.d/10-app.ini:/usr/local/etc/php/app.conf.d/10-app.ini:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dominus-admin.rule=Host(`dominus-admin.localhost`)"
      - "traefik.http.routers.dominus-admin.entrypoints=websecure"
      - "traefik.http.routers.dominus-admin.tls=true"
      - "traefik.http.routers.dominus-admin.tls.certresolver=le"
      - "traefik.http.services.dominus-admin.loadbalancer.server.port=80"
    networks:
      - dominus-network

  da-node:
    image: "node:20"
    working_dir: "/home/node/app"
    environment:
      - NODE_ENV=dev
    tty: true
    stdin_open: true
    volumes:
      - ./:/home/node/app
    networks:
      - dominus-network

networks:
  dominus-network:
    external: true

volumes:
  caddy_data:
  caddy_config:
